version: '3.7'

services:
 app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - 3001:3001
    volumes:
      - ./:/home/app/
    networks:
      - app-network


networks:
  app-network:
    driver: bridge